// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBikT9SMm3ZCwSuZBRNDwioiBWp9NerE',
    appId: '1:83464836412:web:58f9e5b4bd67e33d627a39',
    messagingSenderId: '83464836412',
    projectId: 'thaiup-fc958',
    authDomain: 'thaiup-fc958.firebaseapp.com',
    storageBucket: 'thaiup-fc958.appspot.com',
    measurementId: 'G-2WV8VLJX7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgCWYn3cyiiaF-ZuIAmd4xrV_8jStUp30',
    appId: '1:83464836412:android:aca0dc1545b2150a627a39',
    messagingSenderId: '83464836412',
    projectId: 'thaiup-fc958',
    storageBucket: 'thaiup-fc958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmzIFcEbjNngZtm0e7CVBXba11x7Z3FPk',
    appId: '1:83464836412:ios:3332b46665fcb011627a39',
    messagingSenderId: '83464836412',
    projectId: 'thaiup-fc958',
    storageBucket: 'thaiup-fc958.appspot.com',
    iosBundleId: 'com.example.tesgf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmzIFcEbjNngZtm0e7CVBXba11x7Z3FPk',
    appId: '1:83464836412:ios:c4dc830c8a148022627a39',
    messagingSenderId: '83464836412',
    projectId: 'thaiup-fc958',
    storageBucket: 'thaiup-fc958.appspot.com',
    iosBundleId: 'com.example.tesgf.RunnerTests',
  );
}
